version: '3'

services:

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - "27017:27017"
    volumes:
      - /Docker/Mongo:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge